### ISSUE TITLE
out of gpu memory

### ISSUE THREAD

**Issue by jinganglang567** [YuxinWenRick/tree-ring-watermark#17]
sorry to bother you ,sir 
when i run python run_tree_ring_watermark.py --run_name no_attack --w_channel 3 --w_pattern ring --start 0 --end 1 --with_tracking --reference_model ViT-g-14 --reference_model_pretrain laion2b_s12b_b42k --w_seed=100
it go something wrong like  
File "/root/autodl-tmp/tree-ring-watermark/run_tree_ring_watermark.py", line 218, in <module>
    main(args)
  File "/root/autodl-tmp/tree-ring-watermark/run_tree_ring_watermark.py", line 66, in main
    outputs_no_w = pipe(
  File "/root/miniconda3/envs/tree/lib/python3.10/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/root/autodl-tmp/tree-ring-watermark/modified_stable_diffusion.py", line 175, in __call__
    noise_pred = self.unet(latent_model_input, t, encoder_hidden_states=text_embeddings).sample
  File "/root/miniconda3/envs/tree/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1190, in _call_impl
    return forward_call(*input, **kwargs)
  File "/root/miniconda3/envs/tree/lib/python3.10/site-packages/diffusers/models/unet_2d_condition.py", line 424, in forward
    sample, res_samples = downsample_block(
  File "/root/miniconda3/envs/tree/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1190, in _call_impl
    return forward_call(*input, **kwargs)
  File "/root/miniconda3/envs/tree/lib/python3.10/site-packages/diffusers/models/unet_2d_blocks.py", line 777, in forward
    hidden_states = attn(hidden_states, encoder_hidden_states=encoder_hidden_states).sample
  File "/root/miniconda3/envs/tree/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1190, in _call_impl
    return forward_call(*input, **kwargs)
  File "/root/miniconda3/envs/tree/lib/python3.10/site-packages/diffusers/models/attention.py", line 216, in forward
    hidden_states = block(hidden_states, encoder_hidden_states=encoder_hidden_states, timestep=timestep)
  File "/root/miniconda3/envs/tree/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1190, in _call_impl
    return forward_call(*input, **kwargs)
  File "/root/miniconda3/envs/tree/lib/python3.10/site-packages/diffusers/models/attention.py", line 490, in forward
    hidden_states = self.attn1(norm_hidden_states, attention_mask=attention_mask) + hidden_states
  File "/root/miniconda3/envs/tree/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1190, in _call_impl
    return forward_call(*input, **kwargs)
  File "/root/miniconda3/envs/tree/lib/python3.10/site-packages/diffusers/models/attention.py", line 638, in forward
    hidden_states = self._attention(query, key, value, attention_mask)
  File "/root/miniconda3/envs/tree/lib/python3.10/site-packages/diffusers/models/attention.py", line 654, in _attention
    attention_scores = torch.baddbmm(
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 320.00 MiB (GPU 0; 9.77 GiB total capacity; 7.96 GiB already allocated; 42.69 MiB free; 8.08 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

**Comment by YuxinWenRick** [comment]
Hi, this is weird. I used RTX A4000 with memory of 16 gb, but the whole code only used 20% of the memory. Can you first try to run `python run_tree_ring_watermark.py --run_name no_attack --w_channel 3 --w_pattern ring --start 0 --end 1 --with_tracking --w_seed=100` first? (not using the reference model)

**Comment by jinganglang567** [comment]
Hi,it can work but it return a new error like this
Traceback (most recent call last):
  File "/root/autodl-tmp/tree-ring-watermark/run_tree_ring_watermark.py", line 218, in <module>
    main(args)
  File "/root/autodl-tmp/tree-ring-watermark/run_tree_ring_watermark.py", line 166, in main
    wandb.log({'clip_score_mean': mean(clip_scores), 'clip_score_std': stdev(clip_scores),
  File "/root/miniconda3/envs/tree/lib/python3.10/statistics.py", line 828, in stdev
    var = variance(data, xbar)
  File "/root/miniconda3/envs/tree/lib/python3.10/statistics.py", line 767, in variance
    raise StatisticsError('variance requires at least two data points')
statistics.StatisticsError: variance requires at least two data points

**Comment by jinganglang567** [comment]
and when i change the python file like this
if len(data) >= 2:
    std_dev = stdev(data)
else:
    std_dev = 0

and it workded 
but it warnings The following part of your input was truncated because CLIP can only handle sequences up to 77 tokens: ['jeremy lipkin and giuseppe dangelico pino and michael garmash and rob rey']

**Comment by YuxinWenRick** [comment]
Hi, yeah, I think you may ignore this warning because some of the prompts in the [dataset](https://huggingface.co/datasets/Gustavosta/Stable-Diffusion-Prompts) we are using are longer than the maximum input length of CLIP, so it automatically truncates the prompts. This should be fine.
